# permissions for end users to view openshiftbuilds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: openshiftbuild-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: openshiftbuild-viewer-role
rules:
- apiGroups:
  - operator.openshift.io
  resources:
  - openshiftbuilds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.openshift.io
  resources:
  - openshiftbuilds/status
  verbs:
  - get
