---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - operator.openshift.io
  resources:
  - openshiftbuilds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.openshift.io
  resources:
  - openshiftbuilds/finalizers
  verbs:
  - update
- apiGroups:
  - operator.openshift.io
  resources:
  - openshiftbuilds/status
  verbs:
  - get
  - patch
  - update
